# Generated by Django 3.0.5 on 2021-02-25 06:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('types', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('toppings', django_mysql.models.ListTextField(models.CharField(max_length=30), size=100)),
            ],
        ),
    ]
